services:
  api:
    container_name: pizzaria-backend
    build:
      context: ../pizzaria-fullstack-application
      args:
        DATABASE_URL: "postgresql://exemplouser:exemplosenha@db:5432/pizzaria?schema=public"
        JWT_SECRET: qlqSecret
      dockerfile: ./backend/Dockerfile
    ports:
      - "3333:3333"
    restart: always
    environment:
      DATABASE_URL: "postgresql://exemplouser:exemplosenha@db:5432/pizzaria?schema=public"
      JWT_SECRET: qlqSecret
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: pizzaria-db
    restart: always
    environment:
      - POSTGRES_USER=exemplouser
      - POSTGRES_PASSWORD=exemplosenha
      - POSTGRES_DB=pizzaria
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ../pizzaria-fullstack-application
      dockerfile: ./frontend/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://api:3333
    environment:
      - NEXT_PUBLIC_API_URL=http://api:3333
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - api
